### ISSUE TITLE
How to do a proper release of a beta version?

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/pretested-integration-plugin#107]
It is possible to perform a 'proper' beta release for the experimental update center.

**Comment by MadsNielsen** [comment]
In short according to this: https://jenkins.io/blog/2013/09/23/experimental-plugins-update-center/

If you put beta or alpha in the version you're releasing. It will end up only visible to the experimental update center.

**Comment by buep** [comment]
Good with a comment, we can close this now.
