### ISSUE TITLE
Prepare a beta release by updating Maven configuration and developing Jenkins job

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/pretested-integration-plugin#112]
This issue also has to do with the following:

1. Setting up credentials so that we can push to jenkins-ci.org artifactory and push commits to repo
2. Creating the intial skeleton for a release. 
3. Initial JobDSL for this to be possible.

**Comment by MadsNielsen** [comment]
This issue also has to do with the following:

1. Setting up credentials so that we can push to jenkins-ci.org artifactory and push commits to repo
2. Creating the intial skeleton for a release. 
3. Initial JobDSL for this to be possible.

**Comment by MadsNielsen** [comment]
This issue has been skipped. We've prepared a beta release using the old pipeline. The task should be about making this possible on our new cloud based Jenkins server using docker images. 

Does this really need the GitPhlow tag? Is it somthing that blocks 3.0.0 release?

**Comment by buep** [comment]
There is a beta.2 release out there, released from our existing build and delivery pipeline http://code.praqma.net/ci/view/Open%20Source%20Pipelines/view/Pretested%20Integration%20Plugin%20-%20build%20pipeline/
