### ISSUE TITLE
Manual validation of latest beta before doing the real release

### ISSUE THREAD

**Issue by buep** [Praqma/pretested-integration-plugin#116]
Use the beta to install on a Jenkins and validate our usual happy day and non-happy day scenarios.

I propose to install the beta version on our cloud Jenkins and run it there for a few days with our website pipelines.

Try also to play a bit with it manually in some temporary test jobs.

You need to install it first in our cloud jenkins https://github.com/Praqma/praqma-jenkins/issues/73

**Comment by MadsNielsen** [comment]
@buep  Done. I've installed the plugin and updated our DSL with the web  pipeline and the pipeline examples all with success. 

We'll let it run for a few days see if issues pop up, and in case everything seems in order we'll do the final release midweek.

**Comment by MadsNielsen** [comment]
Been running for 2 days now with now issues. Closing
