### ISSUE TITLE
Failing branch keeps triggering the build

### ISSUE THREAD

**Issue by MichaelMadsen** [Praqma/pretested-integration-plugin#121]
This one needs either more reports, or someone to investigate.

We had a case with the praqma.com pipeline where it was triggered on every SCM poll, every 2 minutes. Always the same branch with a merge conflict, always failing.
https://jenkins.praqma.cloud/job/Web_www.praqma.com-integrate/850/console

**How to investigate this issue:**
In a controlled test environment, with SCM polling enabled, make a `ready` branch with something that fails to auto-merge to the integration branch. Confirm that SCM is only triggered once, and not continuously.

Possibly related to #120

**Comment by buep** [comment]
The pretested integration plugin isn't responsible for triggering the job at all, it is the git scm part. We just get control afterwards.
