### ISSUE TITLE
Allow users to shorten commit messages

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/pretested-integration-plugin#123]
When integrating very large changesets the commit message becomes very large and hard to read. Allow for an option to make this simpler.

**Comment by buep** [comment]
Sad to see a feature like this being accepted in this project, that always had an approach to honor DORIT principles, which isn't integrating big change sets. Thus helping users integrate big change sets, doesn't lead them in the right direction of doing the right thing - integrating often.

Probably earlier owners like me and Lars failed in communicating that priority ;-)

**Comment by MadsNielsen** [comment]
@buep This is very likely to change soon, we might amend to this commit and change the approach, we're not released yet. We've got a customer who needs to merge very large changesets with the Accumulated strategey, and on windows you cannot execute a command with more than 8192 chracters...this is a problem if your commit message is 80000 characters....We might eventually decide to truncate changeset to allow it work on windows. 

It's easier to do this, than to change the behaviour of the customer :)

**Comment by MadsNielsen** [comment]
One thing to also note, the default settings in the plugin are the DORIT principles, if you're doing it right (using the plugin) you don't need to change a thing, all additives are optional, and not required. Eventually we're hoping that the customer will be using the plugin without all the workarounds enabled... :smile:
