### ISSUE TITLE
Support pipeline plugin

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/pretested-integration-plugin#18]
I'm trying to figure out how to do pretested in pipeline script
So far, I got this - it is close but I can't get it to work

node {
    wrap([$class: 'org.jenkinsci.plugins.pretestedintegration.PretestedIntegrationBuildWrapper', scmBridge: [$class: 'org.jenkinsci.plugins.pretestedintegration.scm.git.GitBridge', integrationStrategy: [$class: 'org.jenkinsci.plugins.pretestedintegration.scm.git.SquashCommitStrategy'], branch: 'master', repositoryName: [origin']]) {

```
  checkout([$class: 'GitSCM',
         branches: [[name: '*/ready/**']],
         doGenerateSubmoduleConfigurations: false,
         extensions: [[$class: 'CleanBeforeCheckout']],
         submoduleCfg: [],
         userRemoteConfigs: [[credentialsId: 'jenkins', url: env.SOURCE_REPO]]]) 

 sh '.......'

[$class: 'org.jenkinsci.plugins.pretestedintegration.PretestedIntegrationPostCheckout']
}
```

} 

I'm missing DSL support + it would be great if someone could help me with this snippet so I can progress with what I'm doing

**Comment by buep** [comment]
Hi @Andrey9kin 

Is the work for a JOSRA member or is a customer paying?

Since you estimated the issue, do you plan to work on it?

**Comment by Andrey9kin** [comment]
@buep I don't really have the knowledge to fix this myself. Well, I could but that will take time that's why I hope that someone could fix it for me. Results of this will be used by the JOSRA member.

We need to start building knowledge about pipeline plugin and adapt out plugins to be used in pipeline scripts. More or less the same story as with JobDSL

**Comment by buep** [comment]
I assigned labels and assigned to Thierry, since he did the job dsl.

Let's do it as josra work and this plugin will be the first supporting pipeline dsl.

**Comment by Andrey9kin** [comment]
@buep Super! I'm looking forward to it! @praqma-thi you are very welcome ping me if you need more details or feedback

**Comment by buep** [comment]
Please groom this one....

**Comment by praqma-thi** [comment]
I've been nosing around on this and it seems more complicated than adding Job DSL support.

There's a [big checklist](https://github.com/jenkinsci/pipeline-plugin/blob/master/DEVGUIDE.md) of points your plugin should adhere to if you want to start supporting Pipeline. Besides that, there seem to be ways to make it easier to use inside Pipeline through the use of clever defaults and whatnot.

Briefly reading over the checklist, I have to conclude that Pretested Integration simply isn't compatible with Pipeline. So I don't think we can fix your snippet.

We'll have to go through the entire checklist with the code at hand and list all the changes we'll have to make, changing the easy ones as we go along. There's a few points on the checklist that may cause some issues, like being unable to rely on AbstractBuild/AbstractProject.

**Comment by buep** [comment]
Then this case just becomes "Research support for pipeline plugin" and you estimate the above comment you just did.... implement the easy things that moves us forward regarding supporting pipeline plugin, but doesn't break existing stuff and look at the needed effort on the rest - comes with better estimate, including design proposal for the larger changes.

How  much effort would you need for such research and small changes?

**Comment by praqma-thi** [comment]
I think we should spend a large on it, have me and Mads discuss and tackle it for half a day and see what we get out of it. It's a quick way to get a decent overview and information to plan on how to support it, at least.

**Comment by praqma-thi** [comment]
I created the issue to investigate Pipeline support. It still lacks a milestone, however.
Are we doing this on Josra time? When's a good deadline?

**Comment by bicschneider** [comment]
@MadsNielsen : Please add your investigation here...

**Comment by MadsNielsen** [comment]
My conclusions: 

1. It is not going to be possible to just convert the plugin to be usable with Pipeline. 
2. We would need to change all our AbstractProject<?,?> references to Job<?,?> 
3. We would need to change all AbstractBuild<?,?> references to to Run<?,?>

The hard part is the fact that we are tighly coupled with the Git plugin, more specifically we rely on the ability to obtain the configured Git client from the plugin and the associated actions. In a FreeStyle Project, that is easilly obtained by calling .getScm() on a Pipeline job, the SCM can be placed in any context, and it is not possible to obtain a reference to the SCM using the Job<?,?> object. 

We need to figure out an alternative way to make this possible, which was briefly outlined in #21

**Comment by buep** [comment]
Do we want to take further action on this after the research and conclusion from #21 ?

I would like funding for it, at least partly since it seems rather big task.

**Comment by MadsNielsen** [comment]
Agreed, this functionality requires funding before work should start.

**Comment by buep** [comment]
Thus I remove need grooming label - not is just lies on our backlog.

**Comment by Andrey9kin** [comment]
@buep let's bring it on the next Josra gathering perhaps we can get more members to chip in

**Comment by buep** [comment]
I'm closing this, as we now have SoW out based on discussions from the Code Alliance 6th gathering.
Anything that might be missing after that delivery can be made as additional features.

See #37
