### ISSUE TITLE
Fix pom file so release can be performed (case 14713)

### ISSUE THREAD

**Issue by ReleasePraqma** [Praqma/pretested-integration-plugin#20]

**Comment by buep** [comment]
Why are our ReleasePraqma user creating github issues?

**Comment by MadsNielsen** [comment]
@buep My mistake. I was logged in as ReleasePraqma as i made the issue. Only discovered after issue was created.

**Comment by buep** [comment]
Not done - you have failing build: http://code.praqma.net/ci/view/Open%20Source%20Pipelines/view/Pretested%20Integration%20Plugin%20-%20build%20pipeline/job/pretested-integration-plugin_sync-all-repositories/15/

**Comment by buep** [comment]
done?

**Comment by MadsNielsen** [comment]
Fixed in 96eedcb7394c5c6f57cc67cac2062b85ae6adae4
