### ISSUE TITLE
Git plugin 'nonexisting_workspace' triggers a new build and pretested fails with non-existing branch/sha1

### ISSUE THREAD

**Issue by bicschneider** [Praqma/pretested-integration-plugin#22]
```
This page captures the polling log that triggered this build.

Started on Jun 29, 2016 2:20:00 AM
Workspace is offline.
Scheduling a new build to get a workspace. (nonexisting_workspace)
Done. Took 1 ms
Changes found
```

->

```
Seen 2 remote branches
Checking out Revision c8676707a1a02a3bfa574d18af2f009a9c4dc831 (origin/ready/11_var_expansion_not_working)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c8676707a1a02a3bfa574d18af2f009a9c4dc831
FATAL: Could not checkout c8676707a1a02a3bfa574d18af2f009a9c4dc831
hudson.plugins.git.GitException: Could not checkout c8676707a1a02a3bfa574d18af2f009a9c4dc831
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:1992)
```

This becomes a more and more significant problem as node/agent/slaves are more and more dynamic and autogenerated slaves and not always online scenario.

Option
-  fix Git plugin of the need to use workspace as polling for wild-carded branch pattern. Is it possible?
  - using `git ls-remote origin`
- Abort/(not fail) the build if the build does not result in a integration-try.

It is also related to: https://github.com/Praqma/pretested-integration-plugin/issues/8

**Comment by buep** [comment]
I don't think this is related to PIP - we just take action when a job is started. We can't do anything else.
With dynamic slaves you shouldn't use a workspace for polling. I don't think that is the recommended way to configure git SCM job.

**Comment by bicschneider** [comment]
This should be fixed in the Git Plugin - if need Open an issue in that : https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin

**Comment by MadsNielsen** [comment]
Let's just close this. This is a Git plugin issue so i dont think we want it here.
