### ISSUE TITLE
Ready branch should always be deleted - independent from result

### ISSUE THREAD

**Issue by buep** [Praqma/pretested-integration-plugin#25]
The ready branch should always be deleted, what-ever the result is.
We like to ensure there is always cleaned up after an integration build have been kicked off.
- Even if the result is that the integration failed, due to build failure, merge failure or what-ever.

The background for this choice is to make it easier to push again, and always have the same state.
It makes the workflow simpler when failure arise. For example if it was a temporary failure, you just push again. If you need to fix something, you push change your branch, and push again.

In #24 there is a background discussion for this feature request.

**Comment by sofusalbertsen** [comment]
Some developers @napatech told us they want this feature.
Do we have an estimate on how long it would take to make this?

**Comment by buep** [comment]
@praqma-thi - estimate?

**Comment by praqma-thi** [comment]
Negligable amount of work.
In GitBridge.java, move line 483 outside its conditional block.

Probably want to reword some of the logging messages, though.

**Comment by buep** [comment]
And them some tests that either needs to be updated, or created to check that we actually do delete the branch in all circumstances (fail, success, unstable...).

Then we need to update the documentation, the drawing or workflows description and we might.

Should we bump major version, to signal breaking changes in case some-one depends on not deleting branches? I know it isn't breaking in the usual sense... but somehow we might have users relying on current way of working.

Could we also get one of those red description and warning line when looking at the plugin update page in Jenkins? Some plugins have that when "breaking changes". Can we control that?

**Comment by praqma-thi** [comment]
Yeah that's just a page styling thing.

**Comment by sofusalbertsen** [comment]
Why not make an option here?
Or am i getting option-titis (the decease of wanting more options)?

**Comment by buep** [comment]
The strategy behind PIP have always been to keep it very simple and easy to use, thus basically no options and then plugin will do the right thing. Nothing else!

So we in general don't like options in this plugin - that have earlier been the strategy.

**Comment by lakruzz** [comment]
I'm marking this one for "up next"  let's compile a feature packet for a SoW and find a sponsor.

**Comment by lakruzz** [comment]
Marking this as medium, based on @praqma-thi:

> Negligable amount of work.

...and then some documentation and testing

**Comment by buep** [comment]
Should go into the SoW from 5.th gathering in code-alliance... it fits well with the features we agreed on there.

**Comment by buep** [comment]
Will be fixed as part of #38
