### ISSUE TITLE
404 on CoDe:U Git Flow - a Continuous Delivery Approach from jenkins wiki

### ISSUE THREAD

**Issue by carmosin** [Praqma/pretested-integration-plugin#28]
The page https://wiki.jenkins-ci.org/display/JENKINS/Pretested+Integration+Plugin  contains a link to a no longer existing file.

"CoDe:U Git Flow - a Continuous Delivery Approach" http://www.praqma.com/resources/papers/git-flow

**Comment by buep** [comment]
Fixed https://wiki.jenkins-ci.org/pages/diffpagesbyversion.action?pageId=67568254&selectedPageVersions=124&selectedPageVersions=123
