### ISSUE TITLE
Minutes for PIP Plugin Workshop @CoDe6

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/pretested-integration-plugin#36]
## Talking Points
 - Consensus: Freestyle jobs, generated by JobDSL widely used, 
 - Inherited Jenkins setup, moving towards the Pipeline job type
 - Brief explanation of Different Jobs (Matrix Job type, Freestyle)
 - Talks about branch context switching

## Pipeline
Focus on following the development of Jenkins. 

## Branch context switching 
 - Who came up with the idea? 
 - Talks about implementation details. Configurable names?
   1. Merge
   2. Build
   3. Push 
 - Tagging? Signalling?  --> 
 - Task systems, smart commits
 
Attendants: Man Diesel, Kamstrup, Gul & Gratis, Napatech

## Unstable states
 
Operations issues, if build server is failing.
Failure states, configuring to continue even if merge failed. 

## Results
1. We will come up with an SoW for Pipeline compatibility
2. We'll describe the branch context feature in an SoW

**Comment by MadsNielsen** [comment]
![dsc_0326](https://cloud.githubusercontent.com/assets/1484793/25519423/0a519e12-2bf8-11e7-8fee-6d676625b2ac.JPG)

**Comment by buep** [comment]
Closing this - we have written two SoW. See #37 and #38
