### ISSUE TITLE
Pip pre-grooming meeting

### ISSUE THREAD

**Issue by groenborg** [Praqma/pretested-integration-plugin#45]
Share knowledge of the plugin:
- Architecture
- Design
- Pipeline compliancy details and issues

**Comment by MadsNielsen** [comment]
Claus's preliminary work: https://github.com/bicschneider/pretested-integration-plugin (branch pretestedAsGitExtension)

**Comment by MadsNielsen** [comment]
Other meeting summary: https://github.com/Praqma/pretested-integration-plugin/issues/44

**Comment by groenborg** [comment]
## Pipeline compliancy

### Problem
The SCM step is isolated in pipeline jobs and therefore we cannot access the credentials of the configured git. 

### Solution 
Make a plugin extension to git that will add an advanced option to use pip in the SCM step, so the logic of pip is executed there.

**Comment by groenborg** [comment]
no abstract project for pipeline compliancy

**Comment by groenborg** [comment]
Publisher is optional and can be abstracted away when working on checkout, which is non-optional

**Comment by groenborg** [comment]
Use this as en example of the extension name
https://github.com/Praqma/codesonar-plugin/blob/master/src/main/java/org/jenkinsci/plugins/codesonar/CodeSonarPublisher.java#L325-L327
