### ISSUE TITLE
Extract phlow logic to separate library

### ISSUE THREAD

**Issue by groenborg** [Praqma/pretested-integration-plugin#48]
The phlow logic will exists in both freestyle jobs and and pipeline/workflow, so extracting it to a separate library will make sense to avid code duplication.

- Avoid references to Jenkins library

**Comment by groenborg** [comment]
@buep The formulation may be a bit off, we are not talking about an external library (separate jar file) it's simple moving the code to avoid duplication which will be hard to maintain and introduce legacy. But it needs to be groomed but first when @kryptag and @MadsNielsen have started working on pipeline compatibility and we know our dependencies.

**Comment by buep** [comment]
This need grooming - break up in more tasks and reference these in this issue.

I understand what the issue is about now, but it should take day... if so I need to have it broken down in smaller tasks of half a day or so. Or an plan for how to do it.

**Comment by groenborg** [comment]
#52 #51 #50 Are issues spawned from this. I will close this issue
