### ISSUE TITLE
Move buildwrapper logic to external class

### ISSUE THREAD

**Issue by groenborg** [Praqma/pretested-integration-plugin#50]
Separate the build wrapper pip logic into a external java class, and remove the domain specific dependencies, so it can be used in the pipeline setup as well

**Comment by kryptag** [comment]
the issue here is to move the already made logic that is used in the buildwrapper, to an Java class that can be used both in the buildwrapper and pipeline

**Comment by groenborg** [comment]
This is also based on wrong assumptions, and will be closed
