### ISSUE TITLE
Implement pipeline SCM build step

### ISSUE THREAD

**Issue by groenborg** [Praqma/pretested-integration-plugin#52]
Use the external class make the plugin pipeline compatible

**Comment by kryptag** [comment]
make sure that the logic is compatible with both pipeline and the other jobs

**Comment by bicschneider** [comment]
**Issue**
It is important that we handle this scenario (comment) which is mentioned on the Git Plugin PreMerge feature. The Jenkinsfile is _not_ merged before loaded..: https://gist.github.com/martinda/b2ece95c2c71ddb4d4a762f0a02561b3#gistcomment-2016232

**An option is to:**
- Detect if we touched the $Jenkinsfile loaded
  - If NO - Never mind
  - If YES - Are if we are in a FF scenario (regardless of no of commits)?
     - If YES - Fine 
     - If NO 
       - A)  Abort/fail the integration and inform the user that the branch need to be rebased in order to 
       - B)  Push the integration commit to development branch + Abort/fail the build: NOTE: This will then trigger the Pipeline again as there is a new commit on the branch.

Could be there is a configuration needed to specify the $Jenkinsfile(s) which need to monitored against the changelog

**Comment by buep** [comment]
Not relevant - can be closed, as Claus implemented most so we will need to make issues on missing stuff.
