### ISSUE TITLE
Decide+Update UI/script names and descriptions

### ISSUE THREAD

**Issue by bicschneider** [Praqma/pretested-integration-plugin#62]
- What should the plugin be called ( rebranding to "Praqma GitPhlow" or "GitPhlow" or stay with the old name(s) etc )? Current implementation the PiP is rebranded to "Praqma GitPhlow" 
- Some variable are now exposed to scripts. What should they be called?
- "@ Symbol" implementation for Pipeline Snippet generator
From: 
``` 
           extensions: [[
                $class: 'PretestedIntegrationAsGitPluginExt',
                    gitIntegrationStrategy : [ $class: 'AccumulatedCommitStrategy' ],
                    integrationBranch : 'masterPipeScriptedSCM',
                    repoName: 'origin'
            ]
....
        step([$class: 'PretestedIntegrationPostCheckout'])
```
to
```
		extensions: [
			gitPhlowIntegration(gitIntegrationStrategy: accumulated(), integrationBranch: 'master', repoName: 'origin')
		]
.....
       gitPhlowUpdateRemote()
```

**Comment by buep** [comment]
Search for "Praqma GitPhlow" and "phlow" - we will keep the existing name to Pretested Integration Plugin.

@bicschneider will commit on this case - there we can find the symbol changes to set nice names in pipeline syntax.

## Deliveries

* Naming must be correct
* Symbols must be consistent and name must match existing terminology (ask if unsure)

**Comment by groenborg** [comment]
I have updated it to 
```
checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [PretestedIntegration(gitIntegrationStrategy: accumulated(), integrationBranch: 'master', repoName: 'origin')], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github-phlow', url: 'https://github.com/Praqma/pretested-integration-plugin.git']]])

```

**Comment by buep** [comment]
Some renaming is missing - I'm on it.

Further I need this to be a bit improved, I'll do that: `checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [PretestedIntegration(gitIntegrationStrategy: squash(), integrationBranch: 'master', repoName: 'origin')], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/Praqma/pretested-integration-plugin']]])`

Also Claus switched default behavior to Accumulated, that is not okay. Needs to stay the same as always - squashed.
Also order in UI of squashed and accummulated is switched...
