### ISSUE TITLE
PiP JobDSL test for GitPluginExt

### ISSUE THREAD

**Issue by bicschneider** [Praqma/pretested-integration-plugin#64]
**Issue**
JobDSL for PiP as GitPluginExt not tried nor tested

**Comment by buep** [comment]
https://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.ScmContext.git
https://wiki.jenkins.io/display/JENKINS/Pretested+Integration+Plugin#PretestedIntegrationPlugin-JenkinsJobDSL

**Comment by buep** [comment]
Related to Thierry's comment https://github.com/Praqma/pretested-integration-plugin/issues/81#issuecomment-339594825 where the old job dsl part comes from a java class.

**Comment by buep** [comment]
We still need to write a test that shows Job DSL works when creating a least freestyle jobs using job dsl.
In the commit above we commented out that test, but I can be enabled again as it is fully valid.

We just need to implement the job dsl support that was removed together with removing the build wrapper. See #81 

## TODO

* enable the removed test
* implement job dsl support again (copy from old version)
