### ISSUE TITLE
Upgrade dependencies and make existing version of plugin work

### ISSUE THREAD

**Issue by buep** [Praqma/pretested-integration-plugin#70]
For the changes on master that implements pipeline compliance in the plugin, there is a lot of dependencies that are upgraded.
Also code changed on the way, and also no one did anything to fix the test.

Now we're back on a test setup that works on my machine. @groenborg and @kryptag please try to checkout this branch https://github.com/Praqma/pretested-integration-plugin/tree/pipeline-compliant and run `mvn clean install` and see if the tests work on your machine as well.

Then you need to spend a timebox of 4 hours upgrading the dependencies - probably one by one - and still make the tests work.
You need to go to the new version of dependencies we need for the latest version on master.

Step by step...

**Comment by buep** [comment]
Use this job to verify it works not only on your machine... this is our white-list environment http://code.praqma.net/ci/job/pretested-integration-plugin_verify-from-Github-Praqma_pipeline-compliant/

**Comment by buep** [comment]
Maybe in the same way I did so we have trace of it... like pushing one change at the time and let the Jenkins job pick it up

http://code.praqma.net/ci/job/pretested-integration-plugin_verify-from-Github-Praqma_pipeline-compliant/changes

**Comment by groenborg** [comment]
Results :

Tests in error: 
  FailedTest.org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite » IllegalArgument

Tests run: 8, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.714 s
[INFO] Finished at: 2017-09-19T16:40:06+02:00
[INFO] Final Memory: 58M/1010M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project pretested-integration: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/simon/Github/praqma/pretested-integration-plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
 
/Users/simon/Github/praqma/pretested-integration-plugin
simon@=Simons-MacBook-Pro-2 $

**Comment by groenborg** [comment]
## Issue

The tests fail when we bump the git-client from version `1.9.1` to `2.x` The major bump breaks backwards compatibility and make the tests fail. Version `2.x` also requires an update to the core from version `1.580` to `1.625` which also makes the test fail in another way. 


To fix the issue we must figure out what version work

**Comment by buep** [comment]
I solved the rest of the bumps for you, only thing we need now is a never Jenkins core and never git-plugin dependency.

You could look for version in their changelog you think work, yes, but we should rather fix our code so it works with the never version.
Classic example of upgrading dependencies and need to fix ones own code.

So stick with the version Mads and Claus chose, and then get the test code to work.

**Comment by groenborg** [comment]
simon [11:24 AM] 
mads hvad er grunden til at vi bumper git clienten og core
at vi går fra `core 1.580.3` til `core 1.625.1`
og fra `1.x` i git til `2.x`

mads.nielsen [11:31 AM] 
Core upgrade er fordi pipeline kræver en nyere version af jenkins core. Du skal ivertifald have workflow med som dependency til dine tests.

**Comment by groenborg** [comment]
## Version Bump

- we bump core from `1.5x` because it supposedly does not support pipeline. 
- we bump git for no other reason than the current used version is 2 years old.

**Comment by groenborg** [comment]
# Findings

Several issues have been found connected to RevWalk in the git client library, both in the Jenkins build job and when running tests locally with this command: 
```
mvn -Dtest=AccumulatedCommitMessageIT#commitMessageShouldOnlyCollectFromOwnBranch test
```
This is just an example of where some of the error occur:
https://github.com/Praqma/pretested-integration-plugin/blob/pipeline-compliant/src/test/java/org/jenkinsci/plugins/pretestedintegration/integration/scm/git/JENKINS_25546_IT.java#L76 

this error also originates in RevWalk
```
FATAL: Error computing merge base
hudson.plugins.git.GitException: Error computing merge base
	at hudson.plugins.git.util.GitUtils.filterTipBranches(GitUtils.java:188)
```

**Comment by groenborg** [comment]
This resource explains the incompatibility between git client v 1.* to 2.x and jgit3 to jgit4

**Comment by groenborg** [comment]
Hi,

Thank you for your feedback. We will investigate the issue

**Comment by groenborg** [comment]
#2

**Comment by buep** [comment]
All right, then please let's close this issue and make a new one on migrating to the new jgit and git client in our code.

It should be timeboxed to medium and should concentrate on fixing only one test so we can estimate the rest of the work.

**Comment by groenborg** [comment]
I have created a new issue where we will fix a tests from our findings in this issue. Look at issue #74
