### ISSUE TITLE
Deprecate MultiScm?

### ISSUE THREAD

**Issue by kryptag** [Praqma/pretested-integration-plugin#75]
## keeping or leaving behind Multi Scm
* with implementation of pipelines in jenkins we also get the opportunity to use multi scm in the pipelines them self, and this is a part of jenkins core.
* the developers of Multi Scm have deprecated their plugin for use in pipeline, after the jenkins core team developed the pipeline plugin where this is implemented. Info on https://wiki.jenkins.io/display/JENKINS/Multiple+SCMs+Plugin
* this update is all about being pipeline compliant and focus on PiP for pipelines, so it would be a good opportunity for us to clean up old plugins that aren't relevant anymore

@buep @groenborg @MadsNielsen Feel free to add your opinions on this topic

**Comment by MadsNielsen** [comment]
My personal preference would be to attempt to not support MultipleSCM's it's not even in version 1.X yet. 

That's my 2 cents. More is less, let's support the optimal and preferred solutions. 

So :+1: for leaving it behind.

**Comment by buep** [comment]
I'll make sure we put this in our updated documentation on the wiki, to let the user know that we're not supporting multiscm and users that really needs more types of scm should consider using pipelines instead.

We will have some tests to clean up as well.
