### ISSUE TITLE
Try test harness with git scm extension

### ISSUE THREAD

**Issue by groenborg** [Praqma/pretested-integration-plugin#77]

**Comment by groenborg** [comment]
<img width="1659" alt="skaermbillede 2017-09-28 kl 15 23 05" src="https://user-images.githubusercontent.com/5576954/30968863-00c48daa-a461-11e7-90d5-bd00c4bc0eef.png">

**Comment by buep** [comment]
We have implemented such a test, see https://github.com/Praqma/pretested-integration-plugin/blob/893ef0d7ab75e65c7d0aa05d93776a866d4c7b66/src/test/java/org/jenkinsci/plugins/pretestedintegration/integration/scm/git/PipAsGitExtensionIT.java#L54
