### ISSUE TITLE
Remove old UI (buildwrapper) and clean up code

### ISSUE THREAD

**Issue by buep** [Praqma/pretested-integration-plugin#81]

**Comment by buep** [comment]
@kryptag is on this

**Comment by praqma-thi** [comment]
Note that there's still usages of the build wrapper in the Job DSL extension: `PretestedIntegrationJobDslExtension.java`.

**Comment by groenborg** [comment]
there is a lot of errors when building the project. The build wrapper is still used in 7 different classes and tests.

**Comment by groenborg** [comment]
Some of this can be removed easily. Are we still interested in keeping compatibility with matrix-jobs, because removing the tests for the matrix jobs will be a simple solution? @buep @praqma-thi
