### ISSUE TITLE
Try to move tests to use git scm extension instead of build wrapper

### ISSUE THREAD

**Issue by buep** [Praqma/pretested-integration-plugin#88]
Timeboxed research  - how many tests can we fix by just  changing the test utils to generate jobs using the git scm extension instead of the build wrapper?

How many tests are left after that to change?

Currently the old test is probably still working, but once we remove the build wrapper logic from the code creating jobs that way will not work, thus all tests will fail.

Use the following Jenkins job as verification of which tests run, so commit and push to the branch called `testing` and let Jenkins verify it works or do not work.

http://code.praqma.net/ci/job/pretested-integration-plugin_verify-from-Github-Praqma_testing-branch/
The first build of the job is executed on master-branch as reference. Next build will run on `testing` branch.

Let me know if it is unclear what code to change.

**Comment by groenborg** [comment]
Is it the TestUtilsFactory we want to change, or is it a specific set of test cases we are trying to move over? 

https://github.com/Praqma/pretested-integration-plugin/blob/1122c8a6821b40ed07c182ed418e07f8ab24eb40/src/test/java/org/jenkinsci/plugins/pretestedintegration/integration/scm/git/TestUtilsFactory.java#L312-L363

**Comment by buep** [comment]
it's the test utils factory... the code snippet we use to configure a jenkins job to pretested integration in many of our tests... 

It should be anything with multiscm ... more like ordinary jobs. E.g. this one https://github.com/Praqma/pretested-integration-plugin/blob/1122c8a6821b40ed07c182ed418e07f8ab24eb40/src/test/java/org/jenkinsci/plugins/pretestedintegration/integration/scm/git/TestUtilsFactory.java#L281 where you can see there is something around the buildwrapper that is the old way https://github.com/Praqma/pretested-integration-plugin/blob/1122c8a6821b40ed07c182ed418e07f8ab24eb40/src/test/java/org/jenkinsci/plugins/pretestedintegration/integration/scm/git/TestUtilsFactory.java#L295 ... and should be using git scm extension setup instead.

There might be more places.

**Comment by groenborg** [comment]
I have removed the build wrapper to my ability in the code, but it seems that all the test cases does not work. They all fail now
