### ISSUE TITLE
Investigate and fix failing tests

### ISSUE THREAD

**Issue by buep** [Praqma/pretested-integration-plugin#89]
In #88 we switched test utils to use git scm extension in the job configuration for test jobs.

We need to fix failing tests and investigate why they seems not to work. 

They didn't fail all of them http://code.praqma.net/ci/job/pretested-integration-plugin_verify-from-Github-Praqma_testing-branch/lastCompletedBuild/testReport/

Please see if those failing are configured wrong with git scm extension or something. Investigate the problem. 

Timeboxed. Commit changes one by one to see the job run again.

**Comment by groenborg** [comment]
I am on it now.. I think the test is redundant because it actually says it is a copy from another test. However I am unsure of the behaviour of the build wrapper compared to the sim extension... are identical repos allowed?

**Comment by buep** [comment]
which test?

We can talk about all the multi repository tests later in our meeting.... but the rest with one repository should be worked on.

If the comments say it is a copy of another, them compare them and if they really are the same delete them with a commit as one commit.
Else delete the wrong comment saying it is is a copy.
