### ISSUE TITLE
Add support for matrix jobs

### ISSUE THREAD

**Issue by groenborg** [Praqma/pretested-integration-plugin#90]
We removed support for matrix builds by the commit mentioned below and when cleaning up #81.

We need to support matrix jobs again - more or less enable the code again by fixing the small implementation issues around parameters to methods not being compliant in latest code.

**Comment by buep** [comment]
Support seems to be temporarily removed so we could clean up build wrapper code, which became obsolete with the git scm extension.
This issue was to make sure we fix it back again before releasing so we could move forward on #81 and finish that task.

**Comment by buep** [comment]
Edited title slightly to match the work done.
