### ISSUE TITLE
Make the plugin warn about not being backwards compatible in the update center

### ISSUE THREAD

**Issue by buep** [Praqma/pretested-integration-plugin#95]
I think it is possible to mark a plugin not being backwards compatible when you see the update in the Update Center. This is good if a human upgrades, scripted upgrades don't see it...

So find out how to do it (timeboxed work) if possible. We would like to warn the user that we're not backwards compatible.

**Comment by MadsNielsen** [comment]
Before spending alot of time on this i asked the question on the jenkinsci dev mailing list. I spent like 30mins googling around but didn't find anything of relevance so i restorted to the mailing list.

**Comment by MadsNielsen** [comment]
@buep  I'm pretty sure you already did this in: https://github.com/Praqma/pretested-integration-plugin/commit/eaf4bab3ed106a1383c17cb1173d10cb80747310  :)

It's the example i got from https://wiki.jenkins.io/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions

**Comment by buep** [comment]
Okay, I see - great. I just added your link as comment in the pom for later reference.
