### ISSUE TITLE
Test with gitsubmodules

### ISSUE THREAD

**Issue by buep** [Praqma/pretested-integration-plugin#99]
We should have a test the verifies for both pipeline and free-style jobs the plugin also works with submodules.

The issues cold be that submodules are not updated after our integration merge locally in the workspace.
There is also a git scm extension that updates submodules, that would be selected if the git repository contains submodules that should be used in the job. But in case that git scm extension runs earlier, before we do then the submodules version will not match the result of the merge if there are changes around submodules merged in.

**Comment by buep** [comment]
Start state:

* `gitrepo1` contains submodule `sub1` with file structure:

gitrepo1/
- sub1/
   -  readmesub.md
- readme.md


Do a change in `gitrepo1`, including a needed change in `sub1`:

* First new commit in `sub1`, e.g. `echo "line" >> readmesub.md && git add readmesub.md && git commit -m "Updated sub"
* then en main repo: echo "updated sub" >> readme.md && git add readme.md && git add sub1 && git commit -m "updated submdule and readme"


No integration on sub1 itself, but the main repo will after integration point to the new version of sub1.

The thing we want to test is to make sure that git submodule updates are called in the right place in the flow to ensure we don't roll back the submodule when integrating the main repo.

**Comment by buep** [comment]
Obviously one need to configure the jenkins job to have the git extension called submodule update used.

**Comment by MadsNielsen** [comment]
I've added the initial draft. @buep wanted to add some comments to the code because he's been helping me with the internals of git submodules.

**Comment by buep** [comment]
I contributed with some refactoring as well as some small code changes and a lot of descriptions.

You can deliver it.
